spring:
  application:
    name: produit-service

  datasource:
    url: jdbc:h2:mem:produit
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
    platform: h2
  h2:
    console:
      path: /h2
      enabled: true
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/