spring:
  datasource:
    url: jdbc:h2:mem:produit
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
    platform: h2
  h2:
    console:
      path: /h2
      enabled: true