spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/serviceClient
    username: QIMAPlatformAPI
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true